### ISSUE TITLE
While using DSoft.System.BluetoothLe plugin for UWP project: Calling UpdateRssiAsync and then reading device Rssi value returns 0

### ISSUE THREAD

**Issue by ShaliAvidzba** [newky2k/DSoft.System.BluetoothLe#17]
Calling UpdateRssiAsync and then reading device Rssi value returns 0, code below works just fine for Android but for UWP it always returs 0
if (await device.UpdateRssiAsync())
{
    Debug.WriteLine("The new rssi value is: {0}", device.Rssi);
}

**Comment by newky2k** [comment]
@ShaliAvidzba  I'll take a look and see if i can fint out what the issue is.

**Comment by newky2k** [comment]
The UWP Bluetooth API doesn't have the ability to sett the RSSI.
